import { type NextPage } from "next";
import Head from "next/head";

import Sidebar from "@/components/Sidebar";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen bg-slate-900">
        <div className="flex min-h-screen">
          <Sidebar />
          <div className="">Content</div>
        </div>
      </main>
    </>
  );
};

export default Home;
