import { type NextPage } from "next";
import Head from "next/head";
import { Container } from "@/components/ui/container";
import Navbar from "@/components/navbar/navbar";
import { Article, Comment, PostNewComment } from "@/components/post";
import { trpc } from "@/utils/trpc";
import { AutoAnimate } from "@/utils/animate";

const POST_ID = "clc2g8hev0001oxe14hg8b1z5";

const Home: NextPage = () => {
  const { data: comments } = trpc.comment.getComments.useQuery({
    postId: POST_ID,
  });

  return (
    <>
      <Head>
        <title>Blog Post App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="sticky top-0 z-50">
        <Navbar />
      </header>
      <main className={`mt-8 min-w-full transition-colors duration-500`}>
        <Container className="flex flex-col gap-6">
          <Article />
          <PostNewComment postId={POST_ID} />
          {/* Comment List */}
          <AutoAnimate className="mt-8 mb-8 flex w-full flex-col gap-6">
            {comments?.map((comment) => (
              <Comment key={comment.id} comment={comment} />
            ))}
          </AutoAnimate>
        </Container>
      </main>
    </>
  );
};

export default Home;
