import { type NextPage } from "next";
import Head from "next/head";
import { Container } from "@/components/atoms/container";
import Navbar from "@/components/navbar/navbar";
import { Article, Comment, PostNewComment } from "@/components/post";
import { trpc } from "@/utils/trpc";
import { AutoAnimate } from "@/utils/animate";

// const comments: IComment[] = [
//   {
//     id: 1,
//     content:
//       "I can't believe how much technology has advanced to allow us to capture such incredible footage of space. It's truly mind-blowing to see all the different types of galaxies and to learn about the different phenomena occurring in the universe. The images are so clear and detailed, it's like I'm looking through a telescope! I could watch this video on repeat for hours, just soaking up all the fascinating information and stunning visuals. Great job!",
//     username: "John Doe",
//     likes: 0,
//     liked: true,
//     replies: [
//       {
//         id: 2,
//         content: "I agree! It's so cool to see the universe in such detail.",
//         username: "Jane Doe",
//         likes: 0,
//         liked: false,
//         replies: [
//           {
//             id: 3,
//             content:
//               "Thank you so much for the kind words! I'm really glad you enjoyed the video and found it informative. It's amazing how much technology has advanced to allow us to capture such incredible footage of space. I'm always amazed by the vastness of the universe and the incredible things that exist out there. I'm glad you were able to appreciate the visuals and the music as well. Thank you for taking the time to watch and comment on the video!",
//             username: "John Doe",
//             likes: 0,
//             liked: false,
//             replies: [],
//             createdAt: new Date("2021-01-01"),
//             updatedAt: new Date("2021-01-01"),
//           },
//         ],
//         createdAt: new Date("2021-01-01"),
//         updatedAt: new Date("2021-01-01"),
//       },
//     ],
//     createdAt: new Date("2021-01-01"),
//     updatedAt: new Date("2021-01-01"),
//   },
//   {
//     id: 4,
//     content:
//       "I love this video! It's so beautiful and relaxing to watch. I could watch it on repeat for hours. The music is so soothing and the visuals are stunning. I love how you included so many different types of galaxies and space phenomena. It's so interesting to learn about the different types of galaxies and to see them in such detail. I'm always amazed by the vastness of the universe and the incredible things that exist out there. Great job!",
//     username: "Jane Doe",
//     likes: 0,
//     liked: false,
//     replies: [],
//     createdAt: new Date("2021-01-01"),
//     updatedAt: new Date("2021-01-01"),
//   },
// ];

const POST_ID = "clbp1cd7r0001n0cs30298277";

const Home: NextPage = () => {
  const { data: comments } = trpc.comment.getComments.useQuery({
    postId: POST_ID,
  });

  return (
    <>
      <Head>
        <title>Blog Post App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="sticky top-0 z-50">
        <Navbar />
      </header>
      <main className={`mt-8 min-w-full transition-colors duration-500`}>
        <Container className="flex flex-col gap-6">
          <Article />
          <PostNewComment postId={POST_ID} />
          {/* Comment List */}
          <AutoAnimate className="mt-8 mb-8 flex w-full flex-col gap-6">
            {comments?.map((comment) => (
              <Comment key={comment.id} comment={comment} />
            ))}
          </AutoAnimate>
        </Container>
      </main>
    </>
  );
};

export default Home;
